simplemooc/simplemooc/course/urls.py
from django.conf.urls import url

#importanto o app courses com views
from simplemooc.course import views


#declaração de url amigaveis para app courses
urlpatterns = [
    url(r'^$', views.index, name='index'),
    #passando parametro via url para consulta de base de dados
    url(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
    url(r'^(?P<slug>[\w_-]+)/inscricao$', views.enrollment, name='enrollment'),
    url(r'^(?P<slug>[\w_-]+)/cancelar-escricao$', views.undo_enrollment, name='undo_enrollment'),
    url(r'^(?P<slug>[\w_-]+)/anuncios$', views.announcements, name='announcements'),
    url(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)$', views.show_announcement, name='show_announcement'),
    url(r'^(?P<slug>[\w_-]+)/aulas/$',views.lessons, name='lessons'),
    url(r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)$',views.lesson, name='lesson'),
     url(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)$', views.material, name='material'),
    #url(r'^(?P<pk>\d+)/$', views.details, name='details'),
]

simplemooc/simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace="core")),
    url(r'^cursos/', include('simplemooc.course.urls', namespace="course")),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace="accounts")),
    url(r'^forum/', include('simplemooc.forum.urls', namespace="forum")),
    url(r'^admin/', admin.site.urls),

]

#configuração e concatenização de url de imagem junto com a url fixa
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/course/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.conf import settings
from django.utils import timezone

from simplemooc.core.mail import send_mail_template



class CourseManager(models.Manager):
#metodo de busca nos campos nome ,descrição e slug
    def search(self,query):
            return self.get_queryset().filter(
            models.Q(name__icontains=query) | \
            models.Q(description__icontains=query) | \
            models.Q(slug__icontains=query)
            )

# classe de criação de tabela cursos
class Course(models.Model):

        name = models.CharField('Nome', max_length=100)
        slug = models.SlugField('Atalho')
        description = models.TextField('Descrição', blank=True)
        start_date = models.DateField('Data de Inicio', null=True, blank=True)
        about = models.TextField('Sobre o Curso', blank=True)
        image = models.ImageField(upload_to='course/images', verbose_name='Imagem', null=True, blank=True)

        created_at = models.DateTimeField('Criado em', auto_now_add=True)
        update_at = models.DateTimeField('Atualizado em', auto_now=True)

#chamando metodo da class CourseManager para realizar buscas
        objects = CourseManager()

#convertendo sainda de object e class para nome do object
        def __str__(self):
            return self.name

#contruindo urls amigaveis de acordo com slug
        @models.permalink
        def get_absolute_url(self):
            return ('course:details',(),{'slug': self.slug })

#retornando somente as lições disponiveis
        def release_lessons(self):
            today = timezone.now().date()
            return self.lessons.filter(release_date__gte=today)

#traduzindo nomes atraves de metas
        class Meta:
            verbose_name = 'Curso'
            verbose_name_plural = 'Cursos'
            ordering = ['name']


class Lesson(models.Model):

    name = models.CharField('Nome', max_length=100)
    description = models.TextField('Descrição', blank=True)
    number = models.IntegerField('Número (ordem)', blank=True, default=0)
    release_date = models.DateField('Data de Liberação', blank=True, null=True)

    course = models.ForeignKey(Course, verbose_name='Curso', related_name='lessons')

    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now_add=True)

    def __str__(self):
        return self.name

    def is_available(self):
        if self.release_date:
            today = timezone.now().date()
            return self.release_date >= today
        return False


    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aulas'
        ordering = ['number']

class Material(models.Model):

    name = models.CharField('Nome', max_length=100)
    embedded = models.TextField('Video embedded', blank=True)
    file = models.FileField(upload_to='lesson/materials', blank=True)

    lesson = models.ForeignKey(Lesson,verbose_name='Aula', related_name='materials')

    def is_embedded(self):
        return bool(self.embedded)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Matérial'
        verbose_name_plural = 'Matériais'





class Enrollment(models.Model):

      STATUS_CHOICES = (
       (0,'Pendente'),
       (1,'Aprovado'),
       (2,'Cancelado'),
      )

      user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário',related_name= 'enrollments')
      course = models.ForeignKey(Course, verbose_name='Curso',related_name='enrollments')
      status = models.IntegerField('Situação', choices=STATUS_CHOICES , default=1, blank=True)
      created_at = models.DateTimeField('criado em', auto_now_add=True)
      updated_at = models.DateTimeField('Atualizado em', auto_now_add=True)

      def active(self):
          self.status = 1
          self.save()

      def is_approved(self):
          return self.status == 1

      class Meta:
          verbose_name = 'inscrição',
          verbose_name_plural = 'inscrições'
          unique_together = (('user','course'),)



class Announcement(models.Model):
       course = models.ForeignKey(Course, verbose_name='Curso',related_name='announcements')
       title = models.CharField('Titulo',max_length=100)
       content = models.TextField('Conteudo')

       created_at = models.DateTimeField('criado em', auto_now_add=True)
       updated_at = models.DateTimeField('Atualizado em', auto_now_add=True)


       def __str__(self):
           return self.title

       class Meta:
            verbose_name = 'Anúncio',
            verbose_name_plural = 'Anúncios'
            ordering = ['-created_at']

class Comment(models.Model):

      announcement = models.ForeignKey(Announcement,verbose_name='Anúncio',related_name='comments')
      user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='usuário')
      comment = models.TextField('Comentário')

      created_at = models.DateTimeField('criado em', auto_now_add=True)
      updated_at = models.DateTimeField('Atualizado em', auto_now_add=True)


      class Meta:
          verbose_name = 'Comentário'
          verbose_name_plural = 'Comentários'
          ordering =['created_at']

def post_save_announcement(instance, created, **kwargs):
    if created:
        subject = instance.title
        context = {
        'announcement': instance
        }
        template_name = 'courses/announcement_mail.html'
        enrollments = Enrollment.objects.filter(
            course=instance.course, status=1
        )
        for enrollment in enrollments:
            recipient_list = [enrollment.user.email]
            send_mail_template(subject, template_name, context, recipient_list)

models.signals.post_save.connect(
    post_save_announcement, sender=Announcement, dispatch_uid='post_save_announcement'
    )

simplemooc/simplemooc/course/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from .models import Comment

from simplemooc.core.mail import send_mail_template

class ContactCourse(forms.Form):

        name = forms.CharField(label="Nome",max_length=100)
        email = forms.EmailField(label='E-mail')
        message = forms.CharField(
            label="Mensagem/Dúvidas",widget=forms.Textarea
        )


        def sendEmail(self,course):
            subject = '[%s] contato' % course
            message = 'Nome: %(name)s; Email: %(email)s;%(message)s'
            context = {
                'name': self.cleaned_data['name'],
                'email': self.cleaned_data['email'],
                'message': self.cleaned_data['message'],
            }

            template_name = 'courses/contact_email.html'
            send_mail_template(subject,template_name,context,[settings.CONTACT_EMAIL])

class CommentForm(forms.ModelForm):

      class Meta:
         model = Comment
         fields = ['comment']

simplemooc/simplemooc/course/views.py
from django.shortcuts import render, get_object_or_404,redirect
#importando o model de cursos para trabalhar com base de dados
from .models import Course ,Enrollment, Announcement,Lesson, Material
#importando formulario de cursos/duvidas
from .forms import ContactCourse, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .decorators import enrollment_required

def index(request):
    #buscando todos os cursos
    courses = Course.objects.all()
    #definindo tamplete a ser renderizado
    templateName = 'courses/index.html'
    #dicionario de dados para passar para pagina de cursos
    context = {
     'courses': courses
    }
    return render(request, templateName,context)

def details(request, slug):
    #buscando curso deacordo com sua chave primaria, caso não exista tranferir usuario para pagina de erro 404.
    course = get_object_or_404(Course, slug=slug)
    #variavel de dicionario de dados
    context = {}
    #verificando se a uma request
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.sendEmail(course,)
            form = ContactCourse()
    else:
        form = ContactCourse()

    #definindo tamplete a ser renderizado
    templateName = 'courses/details.html'
    #dicionario de dados para passar para pagina de cursos
    context['form'] = form
    context['course'] = course
    return render(request, templateName,context)

@login_required
def enrollment(request,slug):
     #buscando curso deacordo com sua chave primaria, caso não exista tranferir usuario para pagina de erro 404.
     course = get_object_or_404(Course, slug=slug)
     enrollment, created = Enrollment.objects.get_or_create(user=request.user,course=course)
     if created:
        # enrollment.active()
         messages.success(request, "Parabéns Você acaba de se escrever ao curso !")
     else:
         messages.info(request, "Ops, Você já esta escrito neste curso.")
     return redirect('accounts:dashboard')

@login_required
def undo_enrollment(request,slug):
    #buscando curso deacordo com sua chave primaria, caso não exista tranferir usuario para pagina de erro 404.
    course = get_object_or_404(Course, slug=slug)
    enrollment = get_object_or_404(Enrollment,user=request.user,course=course)
    if request.method == 'POST':
        enrollment.delete()
        messages.success(request,'Sua inscrição foi cancelada com sucesso')
    template_name = 'courses/undo_enrollment.html'
    context = {
     'enrollment': enrollment,
     'course': course
    }
    return render(request,template_name,context)


@login_required
@enrollment_required
def announcements(request,slug):
    #buscando curso deacordo com sua chave primaria, caso não exista tranferir usuario para pagina de erro 404.
    course = request.course
    context = {}
    context['course'] = course
    context['announcements'] = course.announcements.all()
    template_name = 'courses/announcements.html'
    return render(request,template_name,context)

@login_required
@enrollment_required
def show_announcement(request,slug,pk):
    #buscando curso deacordo com sua chave primaria, caso não exista tranferir usuario para pagina de erro 404.
    course = course = request.course
    announcement = get_object_or_404(course.announcements.all(), pk=pk)
    form = CommentForm(request.POST  or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.announcement = announcement
        comment.save()
        form = CommentForm()
        messages.success(request, 'Seu comentário foi salvo com sucesso!')

    template_name = 'courses/show_announcement.html'
    context = {}
    context['course'] = course
    context['announcement'] = announcement
    context['form'] = form

    return render(request,template_name, context)


@login_required
@enrollment_required
def lessons(request,slug):
    course = request.course
    lessons = course.release_lessons()
    template_name = 'courses/lessons.html'
    if request.user.is_staff:
        lessons = course.lessons.all()
    context = {
        'course': course,
        'lessons': lessons
    }
    return render(request, template_name, context)

@login_required
@enrollment_required
def lesson(request,pk,slug):
    course = request.course
    lesson = get_object_or_404(Lesson, pk=pk, course=course)
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Esta aula não está disponível')
        return redirect('course:lessons', slug=course.slug)
    template = 'courses/lesson.html'
    context = {
        'course': course,
        'lesson': lesson
    }
    return render(request, template, context)

@login_required
@enrollment_required
def material(request, slug, pk):
    course = request.course
    material = get_object_or_404(Material, pk=pk, lesson__course=course)
    lesson = material.lesson
    if not request.user.is_staff and not lesson.is_available():
        messages.error(request, 'Este material não está disponível')
        return redirect('courses:lesson', slug=course.slug, pk=lesson.pk)
    if not material.is_embedded():
        return redirect(material.file.url)
    template = 'courses/material.html'
    context = {
        'course': course,
        'lesson': lesson,
        'material': material,
    }
    return render(request, template, context)

simplemooc/simplemooc/course/templates/courses/announcement_mail.html
{{ announcement.content|linebreaks}}

simplemooc/simplemooc/course/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}
{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'course:announcements' course.slug %}">Anúncios</a></li>
{% endblock %}
{% block dashboard_content %}


{% for announcement in announcements %}
<div class="card box-panel">
  <!--Card content-->
  <div class="card-block">
    <div class="card card-dark">
      <!--Title-->
      <h4 class="card-title bold">
        <a href="{% url 'course:show_announcement' course.slug announcement.pk %}">
        {{ announcement.title }}
       </a>
      </h4>
      <p>
      {{ announcement.content|linebreaks }}
      </p>
      <p>
        <a href="{% url 'course:show_announcement' course.slug announcement.pk %}#comments"><i class="fa fa-comments-o" aria-hidden="true"></i>
          {% with coments_count=announcement.comments.count %}
            {{ coments_count }}
            Comentário{{ announcement.comments.count|pluralize }}
          {% endwith %}
         </a>
      </p>
    </div>
  </div>
  <!--/.Card content-->
</div>
<br>

{% empty %}

<h3 class="pure-u-1 alert alert-info">Nenhum anúncio Criado </h3>

{% endfor  %}
{% endblock  %}

simplemooc/simplemooc/course/templates/courses/contact_email.html
<p><b>Nome:</b>{{ name }}</p>
<p><b>Email:</b>{{ email }}</p>
{{ message|linebreaks}}

simplemooc/simplemooc/course/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
{{ block.super }}
<li><a href="{% url 'course:announcements' course.slug %}">{{ course }}</a></li>
{% endblock breadcrumb %}


{% block menu_options %}
<li class="pure-menu-heading border-button">{{course}}</li>

<li class="pure-menu-item">
  <a href="{% url 'course:lessons' course.slug %}" class="list-group-item"><i class="fa fa-video-camera" aria-hidden="true"></i> Aulas e Materíais
  </a>
</li>

<li class="pure-menu-item">
  <a href="#" class="list-group-item"><i class="fa fa-info-circle" aria-hidden="true"></i> Informações
  </a>
</li>

<li class="pure-menu-item">
  <a href="{% url 'course:announcements' course.slug %}" class="list-group-item">
    <i class="fa fa-envelope" aria-hidden="true"></i> Anúncios
  </a>
</li>

<li class="pure-menu-item">
  <a href="#" class="list-group-item"><i class="fa fa-comments" aria-hidden="true"></i> Forum de Dúvidas
  </a>
</li>
{{ block.super }}
{% endblock  %}

simplemooc/simplemooc/course/templates/courses/details.html
<!doctype html>
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="col-md-12 jumbotron">
    <div class="col-md-offset-1">
        <h3 class="text-header">{{ course.name }}</h3>
        <p>
            {{ course.description }}
        </p>
        <a href="{% url 'course:enrollment' course.slug %}" class="button-success pure-button" ><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Inscreva-se</a>
        <a href="{% url 'course:index' %}" class="button-warning pure-button"> <i class="fa fa-arrow-left" aria-hidden="true"></i> voltar</a>
    </div>

</div>

<div class="container">
    <div class="col-md-12">
        <div class="row"><!--Card-->
            <!--Card Dark-->
            <div class="card card-dark">
                <!--Card content-->
                <div class="col-md-9">
                    <!--Social shares button-->
                    <a class="activator"><i class="fa fa-share-alt"></i></a>
                    <!--Title-->
                    <div class="col-md-3">
                        <p>
                            <b>SOBRE O CURSO</b>
                        </p>
                        <hr>
                    </div>

                    <div class="col-md-10">
                        {{ course.about | linebreaks}}
                    </div>
                    <!--Text-->
                </div>
                <!--/.Card content-->
                <br>
                <div class="col-md-2">
                    <!--Card image-->
                    <div class="view overlay hm-white-slight">
                        {% if course.image %}
                        <img src="{{ course.image.url }}"  class="img-fluid" width="350" height="300" alt="{{ course.name }}">
                        {% else %}
                        <img src="{% static 'img/courses/default.png'%}"  width="350" height="300"  alt="{{ course.name }}">
                        {% endif%}

                        <br><br><br>
                        <b class="doubt">DUVIDAS ?</b>
                        <hr>
                        <a class="pure-button" href="#mensage">
                            Fale Conosco
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="mensage" class="l-box-lrg pure-u-3-5 pure-u-md-2-5">

        <h3>Tire sua dúvida sobre o curso</h3>
        <hr>
        {% if is_valid %}
        <div class="text-center alert-success">
            <p>Mensagem Enviada com sucesso ! :D</p>
        </div>
        {% endif%}
        <form method="POST" class="pure-form pure-form-stacked">
            <fieldset>
                {% csrf_token %}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    {% for error in field.errors %}
                    <ul>
                        <li>{{ error }}</li>
                    </ul>
                    {% endfor %}
                </div>
                {% endif %}
                {% endfor %}

                <button type="submit" class="pure-button button-success">Enviar</button>
            </fieldset>
        </form>
    </div>
</div>

{% endblock %}

simplemooc/simplemooc/course/templates/courses/index.html
<!doctype html>
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1 class="text-header">Lista de Cursos</h1>
            <hr>
            <p>Lista de Cursos disponiveis na Plataforma Simple MOOC.</p>
        </div>
        {% for course in courses %}

        <div class="col-md-12">
            <hr>
            <div class="row"><!--Card-->
                <!--Card Dark-->
                <div class="card card-dark">
                    <div class="col-md-3">
                        <!--Card image-->
                        <div class="view overlay hm-white-slight">
                            <a href="{{ course.get_absolute_url }}">
                            {% if course.image %}
                            <img src="{{ course.image.url }}" class="img-rounded" alt="{{ course.name }}" width="270" height="236">
                            {% else %}
                            <img src="{% static 'img/courses/default.png'%}" class="img-thumbnail" alt="{{ course.name }}" width="260" height="236">
                            {% endif%}
                            </a>
                        </div>
                    </div>
                    <!--/.Card image-->
                    <!--Card content-->
                    <div class="col-md-9">
                        <!--Title-->
                        <a href="{{ course.get_absolute_url }}"><h4 class="card-title">{{ course.name }}</h4></a>
                        <hr>
                        <!--Text-->
                            {{ course.description |linebreaks}}
                        <a href="{{ course.get_absolute_url }}" class="d-flex flex-row-reverse"><h5 class="waves-effect waves-light p-2">Leia Mais <i class="fa fa-chevron-right"></i></h5></a>
                    </div>
                    <!--/.Card content-->
                </div>
            </div>
            </div>
            <!--/.Card Dark-->

            {% empty %}
            <div class="col-md-12 text-center">
                <h1>Nenhum Curso disponivel na Plataforma Simple MOOC.</h1>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
</div>
{% endblock %}

simplemooc/simplemooc/course/templates/courses/lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'course:lessons' course.slug %}">Aulas</a></li>
    <li><a href="{% url 'course:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="card box-panel">
  <!--Card content-->
  <div class="card-block">
    <div class="card card-dark">
    <h2><a href="{% url 'course:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    {{ lesson.description|linebreaks }}
    <p>
        <h4>Material da Aula</h4>
        <table class="pure-table full">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                {% for material in lesson.materials.all %}
                <tr class="{% cycle '' 'pure-table-odd' %}">
                    <td>
                      {{ material }}
                    </td>
                    <td>
                        {% if material.is_embedded %}
                        <a class="pure-button button-secondary" href="{% url 'course:material' course.slug material.pk %}">
                            <i class="fa fa-video-camera" aria-hidden="true"></i> Acessar
                        </a>
                        {% else %}
                        <a target="_blank"  class="pure-button button-warning" href="{{ material.file.url }}">
                            _<i class="fa fa-download" aria-hidden="true"></i>_Baixar
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
</div>
</div>
{% endblock %}

simplemooc/simplemooc/course/templates/courses/lessons.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'course:lessons' course.slug %}">Aulas</a></li>
{% endblock %}

{% block dashboard_content %}
{% for lesson in lessons %}
<div class="card box-panel">
  <!--Card content-->
  <div class="card-block">
    <div class="card card-dark">
    <h2><a href="{% url 'course:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        {{ lesson.description|truncatewords:'20' }}
        <br/>
        <a href="{% url 'course:lesson' course.slug lesson.pk %}" title="">
        <i class="fa fa-eye"></i>
        Acessar Aula
        </a>
    </p>
</div>
</div>
</div>
<br>
{% empty %}
    <h3 class="alert alert-info">
        Nenhuma aula disponível.
    </h3>
{% endfor %}
{% endblock %}

simplemooc/simplemooc/course/templates/courses/material.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
{{ block.super }}
<li><a href="{% url 'course:lessons' course.slug %}">Aulas</a></li>
<li><a href="{% url 'course:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
<li><a href="{% url 'course:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="card box-panel">
  <!--Card content-->
  <div class="card-block">
    <div class="card card-dark">
      <h2><a href="{% url 'course:material' course.slug material.pk %}">{{ material }}</a></h2>
      {{ material.embedded|safe }}
      <p>
        <a class="pure-button button-secondary" href="{% url 'course:lesson' course.slug lesson.pk %}">Voltar</a>
      </p>
    </div>
  </div>
</div>
{% endblock %}

simplemooc/simplemooc/course/templates/courses/show_announcement.html
{% extends "courses/course_dashboard.html" %}
{% block breadcrumb %}
  {{ block.super }}
  <li><a href="{% url 'course:show_announcement' course.slug  announcement.pk%}">{{ announcement }}</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
  <div class="card box-panel">
    <!--Card content-->
    <div class="card-block">
      <div class="card card-dark">
        <!--Title-->
        <h4 class="card-title bold">{{ announcement.title }}</h4>
        <p>
        {{ announcement.content|linebreaks }}
        </p>
        <p>
          <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i>
            {% with coments_count=announcement.comments.count %}
              {{ coments_count }}
              Comentário{{ announcement.comments.count|pluralize }}
            {% endwith %}
           </a>
        </p>
      </div>
    </div>
    <!--/.Card content-->
  </div>
  <br>

  <div class="card box-panel">
    <!--Card content-->
    <div class="card-block">
      <div class="card card-dark">
        <!--Title-->
        <h4 class="card-title bold">
          <a id='comments'>
          <legend>Comentários <a href="#comentar">Comentar</a></legend>
          </a>
        </h4>
        {% for comment in announcement.comments.all  %}
          <b>{{ comment.user }} : {{ comment.created_at|timesince }}</b>
          <p>{{ comment.comment|linebreaksbr}}</p>
          <hr>
        {% empty %}
        <p class="alert alert-info">
          <b>Nenhum comentário para esse anúcio.</b>
        </p>
      {% endfor %}



        <div class="pure-g">
            <div class="l-box-lrg pure-u-3-6 pure-u-md-2-5">
              <h4 id="comentar">Comentário</h4>
                <form action="" method="POST" class="pure-form pure-form-aligned">
                  {% csrf_token %}
                    <fieldset>
                      {% for field in form   %}
                      <div class="pure-control-group">
                          {{ field }}
                          {{ field.errors }}
                      </div>
                      {% endfor %}

                            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                    </fieldset>
                </form>
            </div>
            </div>
      </div>
    </div>
    <!--/.Card content-->
  </div>
{% endblock  %}

simplemooc/simplemooc/course/templates/courses/undo_enrollment.html
{% extends "courses/course_dashboard.html" %}
{% block dashboard_content %}
  <form class="" action="" method="post">
    {% csrf_token %}
    <div class="text-center">
        <h4>Deseja Realmente cancelar a inscricão deste curso " <b>{{ enrollment.course }}</b> " ? <i class="fa fa-frown-o" aria-hidden="true"></i></h4>
        <p></p>
        <button type="submit" class="pure-button button-error"><i class="fa fa-check" aria-hidden="true"></i> Sim</button>
        <a href="{% url 'course:announcements' enrollment.course.slug %}" class="pure-button button-gray"><i class="fa fa-ban" aria-hidden="true"></i> Não Cancelar</a>
    </div>
  </form>
{% endblock dashboard_content %}