simplemooc/simplemooc/core/urls.py
from django.conf.urls import url
#importanto o app core com views
from simplemooc.core import views

#declaração de url amigaveis para app core
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contato/$', views.contact, name='contact'),

]

simplemooc/simplemooc/forum/urls.py
from django.conf.urls import url

#importanto o app forum com views
from simplemooc.forum import views


#declaração de url amigaveis para app forum
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tag/(?P<tag>[\w_-]+)/$', views.index, name='index_tagged'),
    url(r'^respostas/(?P<pk>\d+)/correta$', views.reply_correct, name='reply_correct'),
    url(r'^respostas/(?P<pk>\d+)/incorreta$', views.reply_incorrect, name='reply_incorrect'),
    url(r'^(?P<slug>[\w_-]+)/$', views.thread, name='thread'),
]

simplemooc/simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace="core")),
    url(r'^cursos/', include('simplemooc.course.urls', namespace="course")),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace="accounts")),
    url(r'^forum/', include('simplemooc.forum.urls', namespace="forum")),
    url(r'^admin/', admin.site.urls),

]

#configuração e concatenização de url de imagem junto com a url fixa
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/forum/models.py
from django.db import models
from django.conf import settings

from taggit.managers import TaggableManager

class Thread(models.Model):

    title = models.CharField('Título', max_length=100)
    slug = models.SlugField('Identificador', max_length=100, unique=True)
    body = models.TextField('Mensagem')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Autor', related_name='threads'
    )
    views = models.IntegerField('Visualizações', blank=True, default=0)
    answers = models.IntegerField('Respostas', blank=True, default=0)

    tags = TaggableManager()

    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('forum:thread', (), {'slug': self.slug})

    class Meta:
        verbose_name = 'Tópico'
        verbose_name_plural = 'Tópicos'
        ordering = ['-modified']



class Reply(models.Model):

    thread = models.ForeignKey(
        Thread, verbose_name='Tópico', related_name='replies'
    )
    reply = models.TextField('Resposta')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Autor', related_name='replies'
    )
    correct = models.BooleanField('Correta?', blank=True, default=False)

    # auto_now_add parametro ele captura a hora adicionada manualmente
    # auto_now parametro ele captura a hora arual altomaticamente
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    def __str__(self):
        return self.reply[:100]


    class Meta:
        verbose_name = 'Resposta'
        verbose_name_plural = 'Respostas'
        ordering = ['-correct', 'created']

# Informar resposta Correta e submete-la
def post_save_reply(created, instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()
    if instance.correct:
        instance.thread.replies.exclude(pk=instance.pk).update(
            correct=False
        )

def post_delete_reply(instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()

models.signals.post_save.connect(
    post_save_reply, sender=Reply, dispatch_uid='post_save_reply'
)
models.signals.post_delete.connect(
    post_delete_reply, sender=Reply, dispatch_uid='post_delete_reply'
)

simplemooc/simplemooc/forum/forms.py
from django import forms

from .models import Reply


class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['reply']

simplemooc/simplemooc/forum/views.py
from django.shortcuts import render,redirect , get_object_or_404
from django.views.generic import TemplateView, View, ListView,DetailView
from django.contrib import messages

from django.http import HttpResponse

import json

from .forms import ReplyForm, Reply

from .models import Thread


# class ForumView(View):

#     # template_name = 'forum/index.html'
#     def get(self, request, *args, **kwargs):
#         return render(request, 'forum/index.html')


# class ForumView(TemplateView):

#     template_name = 'forum/index.html'

class ForumView(ListView):

    paginate_by = 4
    template_name = 'forum/index.html'

    def get_queryset(self):
        queryset = Thread.objects.all()
        order = self.request.GET.get('order', '')
        if order == 'views':
            queryset = queryset.order_by('-views')
        elif order == 'answers':
            queryset = queryset.order_by('-answers')
        tag = self.kwargs.get('tag', '')
        if tag:
            queryset = queryset.filter(tags__slug__icontains=tag)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ForumView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        return context



class ThreadView(DetailView):

    model = Thread
    template_name = 'forum/thread.html'

# Contar a quantidade de vizualizações e adicionar mais um quando post for requisitado.
# adicionar mais uma vizualização somente quanto não for o usuario do post

    def get(self, request, *args, **kwargs):
        response = super(ThreadView, self).get(request, *args, **kwargs)
        if not self.request.user.is_authenticated() or \
           (self.object.author != self.request.user):
           self.object.views = self.object.views + 1
           self.object.save()
        return response

# Criar contexto para view diacordo com os parametros da url
    def get_context_data(self, **kwargs):
        context = super(ThreadView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        context['form'] = ReplyForm(self.request.POST or None)
        return context

#submeter fomlulario de respostas de post
    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated():
            messages.error(
                self.request,
                'Para responder ao tópico é necessário ter efetuado login'
            )
            return redirect(self.request.path)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form = context['form']
        if form.is_valid():
            reply = form.save(commit=False)
            reply.thread = self.object
            reply.author = self.request.user
            reply.save()
            messages.success(
                self.request, 'A sua responsta foi enviada com sucesso'
            )
            context['form'] = ReplyForm()
        return self.render_to_response(context)


class ReplyCorrectView(View):

    correct = True

    def get(self, request, pk):
        reply = get_object_or_404(Reply, pk=pk, thread__author=request.user)
        reply.correct = self.correct
        reply.save()
        message = 'Sua Resposta atualizada com sucesso'
        if request.is_ajax():
            data = {'success':True,'message':message }
            return HttpResponse(json.dumps(data),mimetype='application/json')
        else:
            messages.success(request,message)
            return redirect(reply.thread.get_absolute_url())


#Tranformando view paseadas em classes em views paseadas em funções
#chamanda da classe em função
index = ForumView.as_view()
thread = ThreadView.as_view()
reply_correct = ReplyCorrectView.as_view()
reply_incorrect = ReplyCorrectView.as_view(correct=False)

simplemooc/simplemooc/forum/templates/forum/index.html
{% extends "base.html" %}

{% block content %}


<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb breadcrumb-inverse">
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
        </ul>
    </div>

    <div class="pure-g">
        <div class="pure-u-2-24"></div>
        <div class="pure-u-7-24">
            <div class="card box-panel">
                <!--Card content-->
                <div class="card-block">
                    <div class="card card-dark">
                        <ul class="pure-menu-list">
                            <li class="pure-menu-heading border-button">
                                <a class="pure-menu-link decoration-none"  href="{% url 'forum:index'%}">
                            Tópicos do Fórum
                                </a>
                            </li>
                            <li class="pure-menu-item">
                                <a class="pure-menu-link decoration-none"  href="?order=">
                                    <i class="fa fa-refresh"></i>
                                    Mais Recentes
                                </a>
                            </li>
                            <li class="pure-menu-item">
                                <a class="pure-menu-link decoration-none"  href="?order=views">
                                    <i class="fa fa-eye"></i>
                                    Mais Visualizados
                                </a>
                            </li>
                            <li class="pure-menu-item">
                                <a class="pure-menu-link decoration-none"  href="?order=answers">
                                    <i class="fa fa-comments-o"></i>
                                    Mais Comentados
                                </a>
                            </li>
                            <li class="pure-menu-heading border-button">Tags</li>
                            <br>
                            {% for tag in tags %}
                            <a href="{% url 'forum:index_tagged' tag.slug %}" class="tags-menu decoration-none">
                                <i class="fa fa-tag"></i>
                                {{ tag }}
                            </a>
                            {% empty %}
                            <p class="list-group-item" >Não existe nenhuma tag</p>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="pure-u-1-24"></div>
        <div class="pure-u-12-24">
            <div class="inner">
                {% for thread in object_list %}
                <div class="card box-panel">
                    <!--Card content-->
                    <div class="card-block">
                        <div class="card card-dark">
                            <h3><a class="bold" href="{{ thread.get_absolute_url }}" title="">{{ thread.title }}</a></h3>
                            <br>
                            <h5 class="bold">
                                Criado por {{ thread.author }} | {{ thread.answers }} resposta{{ thread.answers|pluralize }} | {{ thread.views }} Visualizaç{{ thread.views|pluralize:"ão,ões" }}
                            </h5>
                            <p>
                                <i class="fa fa-tags"></i>
                                Tags:
                                {% for tag in thread.tags.all %}
                                <a href="{% url 'forum:index_tagged' tag.slug %}" title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                                {% endfor %}
                                <div class="text-right">
                                    <a class="fright" href="{{ thread.get_absolute_url }}" title="">Atualizado a {{ thread.modified|timesince }} atrás</a>
                                </div>
                            </p>
                        </div>
                    </div>
                </div>
                <br>
                {% empty %}
                <div class="row">
                    <div class="text-center">
                        <h4 class="alert alert-info">
                            Nenhuma descução foi iniciada
                        </h4>
                    </div>
                </div>
                {% endfor %}
                <ul class="pagination pagination-centered">
                    {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Anterior</a>
                    </li>
                    {% endif %}
                    {% for page in paginator.page_range %}
                    <li{% if page == page_obj.number %} class="active"{% endif %}>
                    <a href="?page={{ page }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">{{ page }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Próxima</a>
                </li>


                {% endif %}
            </ul>
        </div>
    </div>

</div>
</div>
</div>



{% endblock %}

simplemooc/simplemooc/forum/templates/forum/thread.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb breadcrumb-inverse">
            <li><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'forum:index' %}">Fórum de Discussões</a></li>
            <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
        </ul>
    </div>
    <div class="pure-g">
        <div class="pure-u-2-24"></div>
        <div class="pure-u-7-24">
            <div class="card box-panel">
                <!--Card content-->
                <div class="card-block">
                    <div class="card card-dark">
                        <ul class="pure-menu-list">
                            <li class="pure-menu-heading border-button">
                                <a class="pure-menu-link decoration-none"  href="{% url 'forum:index'%}">
                                    Tópicos do Fórum
                                </a>
                            </li>
                            <li class="pure-menu-item">
                                <a class="pure-menu-link decoration-none"  href="?order=">
                                    <i class="fa fa-refresh"></i>
                                    Mais Recentes
                                </a>
                            </li>
                            <li class="pure-menu-item">
                                <a class="pure-menu-link decoration-none"  href="?order=views">
                                    <i class="fa fa-eye"></i>
                                    Mais Visualizados
                                </a>
                            </li>
                            <li class="pure-menu-item">
                                <a class="pure-menu-link decoration-none"  href="?order=answers">
                                    <i class="fa fa-comments-o"></i>
                                    Mais Comentados
                                </a>
                            </li>
                            <li class="pure-menu-heading border-button">Tags</li>
                            <br>
                            {% for tag in tags %}
                            <a href="{% url 'forum:index_tagged' tag.slug %}" class="tags-menu decoration-none">
                                <i class="fa fa-tag"></i>
                                {{ tag }}
                            </a>
                            {% empty %}
                            <p class="pure-menu-item" >Não existe nenhuma tag</p>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="pure-u-1-24"></div>
        <div class="pure-u-12-24">
            <div class="inner">
                <div class="card box-panel">
                    <!--Card content-->
                    <div class="card-block">
                        <div class="card card-dark">
                            <h2>{{ object }}</h2>
                            {{ object.body|linebreaks }}
                            <h5>
                                Criado por {{ object.author }}
                            </h5>
                            <p>
                                <i class="fa fa-tags"></i>
                                {% for tag in object.tags.all %}
                                <a href="{% url 'forum:index_tagged' tag.slug %}" title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                                {% endfor %}
                                <a class="fright" href="" title="">Criado a {{ object.created|timesince }} atrás</a>
                            </p>
                        </div>
                    </div>
                </div>
                <br>
                <div class="card box-panel" id="div-comments">
                    <!--Card content-->
                    <div class="card-block">
                        <div class="card card-dark">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-md-10">
                                        <h4 id="comments">Respostas</h4>
                                    </div>
                                    <div class="col-md-2">
                                        <a class="fright bold" href="#add_comment">#Responder</a>
                                    </div>
                                </div>
                            </div>
                                {% for reply in object.replies.all %}
                                <hr/>
                                <p>
                                    <strong>{{ reply.author }}</strong> disse à {{ reply.created|timesince }} atrás:
                                    <br/>
                                    {{ reply.reply|linebreaksbr }}
                                    <br/>
                                    <div class="pure-g">
                                        <div class="pure-u-5-5">

                                            {% if object.author == user %}
                                                <a class="pure-button button-error pure-button reply-cancel-correct-lnk {% if not reply.correct %} hidden {% endif %}" href="{% url 'forum:reply_incorrect' reply.pk %}" >
                                                    <i class="fa fa-ban" aria-hidden="true"></i>
                                                    Cancelar Resposta
                                                </a>

                                                <a class="pure-button button-success pure-button reply-correct-lnk" href="{% url 'forum:reply_correct' reply.pk %}" >
                                                    <i class="fa fa-check-square-o" aria-hidden="true"></i>
                                                    Resposta Correta
                                                </a>

                                            <div class="pure-u-2-5 {% if not reply.correct %} hidden {% endif %}">
                                                <div class="alert-success text-center reply-correct-msg">
                                                    <p>Resposta indicada pelo Autor
                                                        <i class="fa fa-check-square" aria-hidden="true"></i>
                                                    </p>
                                                </div>
                                            </div>

                                            <br class="reply-correct-msg {% if not reply.correct %} hidden {% endif %}">

                                            {% elif reply.correct %}

                                            <div class="pure-u-2-5">
                                                <div class="alert-success text-center">
                                                    <p>Resposta indicada pelo Autor
                                                        <i class="fa fa-check-square" aria-hidden="true"></i>
                                                    </p>
                                                </div>
                                            </div>




                                            {% endif %}
                                        </div>
                                    </div>
                                </p>
                                {% empty %}

                                <div class="alert-info text-center">
                                    <p>Ninguém respondeu ainda.</p>
                                </div>


                                {% endfor %}
                                <hr />
                                <form method="post" class="pure-form pure-form-stacked" id="add_comment">
                                    <fieldset>
                                        {% csrf_token %}
                                        {% for field in form %}
                                        <div class="pure-control-group">
                                            {{ field.label_tag }}
                                            {{ field }}
                                            {{ field.errors }}
                                        </div>
                                        {% endfor %}
                                        <div class="pure-controls">
                                            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                                        </div>
                                    </fieldset>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    {% block scripts %}
<script type="text/javascript">
    $(".reply-cancel-correct-lnk").on("click", function(e){
        e.preventDefault();
        var $this = $(this);
        var $p = $this.closest("p");
        $.get($this.attr('href'), function(data){
            if(data.success){
                $p.find(".reply-correct-msg").addClass('hidden');
                $this.addClass('hidden');
                $p.find('.reply-correct-lnk').removeClass('hidden');
            } else {
                alert(data.message);
            }
        }, "json");
        location.reload();
        return false;
    });
    $('.reply-correct-lnk').on('click', function(e){
        e.preventDefault();
        var $this = $(this);
        var $p = $this.closest("p");
        $.get($this.attr('href'), function(data){
            if(data.success){
                $("#div-comments .reply-correct-msg").addClass('hidden');
                $("#div-comments .reply-cancel-correct-lnk").addClass('hidden');
                $("#div-comments .reply-correct-lnk").removeClass('hidden');

                $p.find(".reply-correct-msg").removeClass('hidden');
                $this.addClass('hidden');
                $p.find('.reply-cancel-correct-lnk').removeClass('hidden');
            } else {
                alert(data.message)
            }
        }, 'json');
        location.reload();
        return false;
    })
</script>
{% endblock %}