simplemooc/simplemooc/accounts/urls.py
from django.conf.urls import  url, include
from django.contrib.auth import views as auth_views
from simplemooc.accounts import views as accounts_views



#declaração de url amigaveis para app core
urlpatterns = [
    url(r'^$', accounts_views.dashboard , name='dashboard'),
    url(r'^entrar/$', auth_views.login,{'template_name':'accounts/login.html'} ,name='login'),
    url(r'^sair/$', auth_views.logout,{'next_page':'core:home'} ,name='logout'),
    url(r'^cadastrar/$', accounts_views.register , name='register'),
    url(r'^editar/$', accounts_views.edit , name='edit'),
    url(r'^editar-senha/$', accounts_views.edit_password , name='edit_password'),
    url(r'^nova-senha/$', accounts_views.password_reset , name='password_reset'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)/$', accounts_views.password_reset_confirm , name='password_reset_confirm')
]

simplemooc/simplemooc/core/urls.py
from django.conf.urls import url
#importanto o app core com views
from simplemooc.core import views

#declaração de url amigaveis para app core
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contato/$', views.contact, name='contact'),

]

simplemooc/simplemooc/forum/urls.py
from django.conf.urls import url

#importanto o app forum com views
from simplemooc.forum import views


#declaração de url amigaveis para app forum
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^tag/(?P<tag>[\w_-]+)/$', views.index, name='index_tagged'),
    url(r'^respostas/(?P<pk>\d+)/correta$', views.reply_correct, name='reply_correct'),
    url(r'^respostas/(?P<pk>\d+)/incorreta$', views.reply_incorrect, name='reply_incorrect'),
    url(r'^(?P<slug>[\w_-]+)/$', views.thread, name='thread'),
]

simplemooc/simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace="core")),
    url(r'^cursos/', include('simplemooc.course.urls', namespace="course")),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace="accounts")),
    url(r'^forum/', include('simplemooc.forum.urls', namespace="forum")),
    url(r'^admin/', admin.site.urls),

]

#configuração e concatenização de url de imagem junto com a url fixa
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/core/models.py
from django.db import models

simplemooc/simplemooc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request,'home.html')

def contact(request):
    return render(request,'contact.html')

simplemooc/simplemooc/core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A layout example that shows off a responsive product landing page.">
  <title>Simple Mooc</title>

  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!--[if lte IE 8]>
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-old-ie-min.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
  <!--<![endif]-->

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

  <!--[if lte IE 8]>
  <link rel="stylesheet" href="css/layouts/marketing-old-ie.css">
  <![endif]-->
  <!--[if gt IE 8]><!-->
  <link rel="stylesheet" href="{% static 'css/marketing.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <script  src="https://code.jquery.com/jquery-3.2.1.js"  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="  crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <!--<![endif]-->
</head>
<body>

  <div class="header">
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
      <a class="pure-menu-heading border-all decoration-none" href="{% url 'core:home' %}">Simple MOOC</a>
      <ul class="pure-menu-list">
        <li class="pure-menu-item"><a href="{% url 'core:home' %}" class="pure-menu-link"><b>Home</b></a></li>
        <li class="pure-menu-item"><a href="{% url 'course:index' %}" class="pure-menu-link">Cursos</a></li>
        <li class="pure-menu-item"><a href="{% url 'forum:index' %}" class="pure-menu-link">Forum</a></li>
        <li class="pure-menu-item"><a href="{% url 'core:contact' %}" class="pure-menu-link">Contato</a></li>
        {% if user.is_authenticated %}
        <li class="pure-menu-item"><a href="{% url 'accounts:dashboard' %}" class="pure-menu-link">Meu Painel</a></li>
        <li class="pure-menu-item"><a href="{% url 'accounts:logout' %}" class="pure-menu-link">Sair</a></li>
        {% else %}
        <li class="pure-menu-item"><a href="{% url 'accounts:login' %}" class="pure-menu-link">Entrar</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
<br><br><br>
<div class="pure-u-24-24 text-center">
  {% for message in messages  %}
        <p class="alert alert-info">{{ message }}</p>
  {% endfor %}
</div>
  {% block content %}{% endblock %}
<br><br>
  <div class="color-footer l-box is-center">
    Simple MOOC - Uma Simples plataforma de ensino a distância.
  </div>
</body>

{% block scripts %}{% endblock scripts %}



</html>

simplemooc/simplemooc/core/templates/contact.html
<!doctype html>
{% extends "base.html" %}
{% block content %}
<div class="content">
    <h2 class="content-head is-center">Dolore magna aliqua. Uis aute irure.</h2>

    <div class="pure-g">
        <div class="l-box-lrg pure-u-3-5 pure-u-md-2-5">
            <form action="" method="" class="pure-form pure-form-aligned">
                <fieldset>
                    <div class="pure-control-group">
                        <input id="name" type="text" placeholder="Nome" autofocus  required>
                    </div>

                    <div class="pure-control-group">
                        <input id="email" type="email" placeholder="Email" required>
                    </div>

                    <div class="pure-control-group">
                        <textarea id="mensage"  class="pure-input-1" placeholder="Mensagem..." required></textarea>
                    </div>

                        <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                </fieldset>
            </form>
        </div>

        <div class="l-box-lrg pure-u-1 pure-u-md-3-5">
            <h4>Contato</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat.
            </p>

            <h4>Mais Informações</h4>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua.
            </p>
        </div>
    </div>
</div>

{% endblock %}

simplemooc/simplemooc/core/templates/home.html
<!doctype html>
{% extends "base.html" %}
{% block content %}
<div class="splash-container">
    <div class="splash">
        <h1 class="splash-head">Simple MOOC</h1>
        <p class="splash-subhead">
            O Simple MOOC visa simpleificar o ensino a distância, provendo ferramentas objetivas de fácil uso para cursos as distância
        </p>
        <p>
            <a href="{% url 'accounts:login' %}" class="pure-button pure-button-primary">INSCREVA-SE</a>
        </p>
    </div>
</div>

<div class="content-wrapper">
    <div class="content">
        <h2 class="content-head is-center">cursos mais buscados.</h2>

        <div class="pure-g">
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">

                <h3 class="content-subhead">
                    Curso de PHP
                </h3>

                <p>
                    <img src="https://laracasts.com/images/series/squares/the-php-practitioner.jpg" class="img-rounded" alt="Cinque Terre" width="304" height="236">
                    Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    Curso de Python 3
                </h3>
                <p>
                    <img src="https://i.ytimg.com/vi/HvgOMjCXMGo/hqdefault.jpg" class="img-rounded" alt="Cinque Terre" width="304" height="236">
                    Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    <i class="fa fa-th-large"></i>
                    Curso de SQL Server
                </h3>
                <p>
                    <img src="https://blogdigicad.files.wordpress.com/2014/05/sql_server.jpg" class="img-rounded" alt="Cinque Terre" width="304" height="236">
                    Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    <i class="fa fa-check-square-o"></i>
                    Curso de bootstrap
                </h3>
                <p>
                    <img src="https://getbootstrap.com/apple-touch-icon.png" class="img-rounded" alt="Cinque Terre" width="304" height="236">
                    Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                </p>
            </div>
        </div>
    </div>

<div class="content-wrapper">
    <div class="content">
        <h2 class="content-head is-center">Excepteur sint occaecat cupidatat.</h2>

        <div class="pure-g">
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">

                <h3 class="content-subhead">
                    <i class="fa fa-rocket"></i>
                    Get Started Quickly
                </h3>
                <p>
                    Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    <i class="fa fa-mobile"></i>
                    Responsive Layouts
                </h3>
                <p>
                    Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    <i class="fa fa-th-large"></i>
                    Modular
                </h3>
                <p>
                    Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                </p>
            </div>
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    <i class="fa fa-check-square-o"></i>
                    Plays Nice
                </h3>
                <p>
                    Phasellus eget enim eu lectus faucibus vestibulum. Suspendisse sodales pellentesque elementum.
                </p>
            </div>
        </div>
    </div>

    <div class="ribbon l-box-lrg pure-g">
        <div class="l-box-lrg is-center pure-u-1 pure-u-md-1-2 pure-u-lg-2-5">
        </div>
        <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-3-5">

            <h2 class="content-head content-head-ribbon">Laboris nisi ut aliquip.</h2>

            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor.
            </p>
        </div>
    </div>
</div>

{% endblock %}