simplemooc/simplemooc/accounts/urls.py
from django.conf.urls import  url, include
from django.contrib.auth import views as auth_views
from simplemooc.accounts import views as accounts_views



#declaração de url amigaveis para app core
urlpatterns = [
    url(r'^$', accounts_views.dashboard , name='dashboard'),
    url(r'^entrar/$', auth_views.login,{'template_name':'accounts/login.html'} ,name='login'),
    url(r'^sair/$', auth_views.logout,{'next_page':'core:home'} ,name='logout'),
    url(r'^cadastrar/$', accounts_views.register , name='register'),
    url(r'^editar/$', accounts_views.edit , name='edit'),
    url(r'^editar-senha/$', accounts_views.edit_password , name='edit_password'),
    url(r'^nova-senha/$', accounts_views.password_reset , name='password_reset'),
    url(r'^confirmar-nova-senha/(?P<key>\w+)/$', accounts_views.password_reset_confirm , name='password_reset_confirm')
]

simplemooc/simplemooc/course/urls.py
from django.conf.urls import url

#importanto o app courses com views
from simplemooc.course import views


#declaração de url amigaveis para app courses
urlpatterns = [
    url(r'^$', views.index, name='index'),
    #passando parametro via url para consulta de base de dados
    url(r'^(?P<slug>[\w_-]+)/$', views.details, name='details'),
    url(r'^(?P<slug>[\w_-]+)/inscricao$', views.enrollment, name='enrollment'),
    url(r'^(?P<slug>[\w_-]+)/cancelar-escricao$', views.undo_enrollment, name='undo_enrollment'),
    url(r'^(?P<slug>[\w_-]+)/anuncios$', views.announcements, name='announcements'),
    url(r'^(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)$', views.show_announcement, name='show_announcement'),
    url(r'^(?P<slug>[\w_-]+)/aulas/$',views.lessons, name='lessons'),
    url(r'^(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)$',views.lesson, name='lesson'),
     url(r'^(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)$', views.material, name='material'),
    #url(r'^(?P<pk>\d+)/$', views.details, name='details'),
]

simplemooc/simplemooc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^', include('simplemooc.core.urls', namespace="core")),
    url(r'^cursos/', include('simplemooc.course.urls', namespace="course")),
    url(r'^conta/', include('simplemooc.accounts.urls', namespace="accounts")),
    url(r'^forum/', include('simplemooc.forum.urls', namespace="forum")),
    url(r'^admin/', admin.site.urls),

]

#configuração e concatenização de url de imagem junto com a url fixa
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/simplemooc/accounts/models.py
import re
from django.db import models
from django.core import validators
#importando models de auth -> AbstractBaseUser , PermissionsMixin, UserManager
#AbstractBaseUser = herança de model campos padrões
#PermissionsMixin = herança de model de grupos e permissões django
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin, UserManager)
from django.conf import settings
from simplemooc.course.models import Course


class User(AbstractBaseUser,PermissionsMixin):

    username = models.CharField(
        'Nome de Usuário', max_length=30,unique=True,
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
            'O Nome de usuário só pode conter letras, digitos ou os '
            'seguintes caracteres: @/./+/-/_','invalid')]
    )
    email = models.EmailField('E-mail',unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está Ativo?',blank=True,default=True)
    is_staff = models.BooleanField('É da equipe ?',blank=True,default=False)
    date_joined = models.DateTimeField('Data de Entrada', auto_now_add=True)


    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class PasswordReset(models.Model):

      user = models.ForeignKey(
       settings.AUTH_USER_MODEL, verbose_name='Usuário',
       related_name= 'resets',
      )
      key = models.CharField('Chave', max_length=100,unique=True)
      created_at = models.DateTimeField('criado em', auto_now_add=True)
      confirm = models.BooleanField('Confirmado?', default=False, blank=True)

      def __str__(self):
        return '{0} em {1}'.format(self.user, self.created_at)

      class Meta:
         verbose_name = 'Nova Senha'
         verbose_name_plural = 'Novas Senhas'
         ordering = ['-created_at']

simplemooc/simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from simplemooc.core.utils import generate_hash_key
from simplemooc.core.mail import send_mail_template
from .models import PasswordReset

User = get_user_model()

class PasswordResetForm(forms.Form):

        email = forms.EmailField(label='E-mail')

        def clean_email(self):
            email = self.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                return email
            raise forms.ValidationError(
                'Nenhum usuário encontrado com esse E-mail'
            )

        def save(self):
            user = User.objects.get(email=self.cleaned_data['email'])
            key = generate_hash_key(user.name)
            reset = PasswordReset(key=key,user=user)
            reset.save()
            template_name = 'accounts/password_reset_mail.html'
            subject = 'Criar uma nova senha de acesso ao Simple MOOC'
            context = {}
            context['reset'] = reset
            send_mail_template(subject,template_name,context,[user.email])



#realizar registro de usuarios
class RegisterForm(forms.ModelForm):

        email = forms.EmailField(label='E-mail')
        password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
        password2 = forms.CharField(label='Confirmação de senha', widget=forms.PasswordInput)

        def clean_password2(self):
            password1 = self.cleaned_data.get('password1')
            password2 = self.cleaned_data.get('password2')
            if password1 and password2 and password1 != password2:
               raise forms.ValidationError('As senhas não são iguais')
            return password2


#travar transissão de save e capturar dados de email e apos isso continuar o commit em base de dados
        def save(self,commit=True):
                user = super(RegisterForm,self).save(commit=False)
                user.set_password(self.cleaned_data['password1'])
                if commit:
                   user.save()
                return user

        class Meta:
            model = User
            fields = ['username','email']


#realizar editar de usuarios
class EditAccountForm(forms.ModelForm):

    #informando quais campos podera ser editados pelo usuario
    class Meta:
        model = User
        fields = ['username','email','name']

simplemooc/simplemooc/accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
#importando formulario de registro de contas do django
from django.contrib.auth.forms import (UserCreationForm , PasswordChangeForm,SetPasswordForm)
#importando auth e login próprio django
from django.contrib.auth import authenticate, login, get_user_model
#importando app django para ser solicitado login para acessar pagina
from django.contrib.auth.decorators import login_required
#importando settings raiz
from django.conf import settings
from django.contrib import messages
#importando formulario personalizado de CRUD de contas de usuarios
from .forms import RegisterForm ,EditAccountForm, PasswordResetForm
from simplemooc.core.utils import generate_hash_key
from simplemooc.course.models import Enrollment

from .models import PasswordReset

User = get_user_model()


@login_required
def dashboard(request):
    #adicionando valor a variavel com camiho do template
    template_name = 'accounts/dashboard.html'
    context = {}
    context['enrollments'] = Enrollment.objects.filter(user=request.user)
    #retornando template index
    return render(request,template_name,context)



#metodo para cadastrar usuarios
def register(request):
    #adicionando valor a variavel com camiho do template
    template_name = 'accounts/register.html'
    #verificando se o metodo de envio é post
    form = RegisterForm(request.POST or None)
        #vereficando se é valido o formulario
    if form.is_valid():
            #salvar informação no db se dados for valido e captura os dados
            user = form.save()
            #pega usuario para automaticamente autêntica-lo e redirecionar para pagina inicial
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request,user)
            return redirect('core:home')
    context = {
        'form' : RegisterForm()
    }

    return render(request,template_name,context)


def password_reset(request):
    template_name = 'accounts/password_reset.html'
    form = PasswordResetForm(request.POST or None)
    context={}
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form

    return render(request,template_name,context)

def password_reset_confirm(request,key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset,key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request,template_name,context)

#metodo para editar dados de usuario
@login_required
def edit(request):
    #adicionando valor a variavel com camiho do template
    template_name = 'accounts/edit.html'
    # criando contexto
    context = {}
    form = EditAccountForm(request.POST or None , instance=request.user)
        #vereficando se é valido o formulario
    if form.is_valid():
             #salvar informação no db se dados for valido e captura os dados
             form.save()
             context['success'] = True
             # mensagem de sucesso se tudo ocorrer bem
    context['form'] = form
    #retornado template juntamente com o dicionario
    return render(request,template_name,context)


#Atualizar a senha de usuario
@login_required
def edit_password(request):
    #adicionando valor a variavel com camiho do template
    template_name = 'accounts/edit_password.html'
     # criando contexto
    context = {}
    form = PasswordChangeForm(data=request.POST or None, user=request.user)
    if form.is_valid():
             #salvar informação no db se dados for valido e captura os dados
             form.save()
             # mensagem de sucesso se tudo ocorrer bem
             context['success'] = True
    context['form'] = form

    return render(request,template_name,context)

simplemooc/simplemooc/accounts/templates/accounts/dashboard.html
<!doctype html>
{% extends "base.html" %}
{% load courses_tags %}
{% block content %}

<div class="pure-g">
  <div class="pure-u-24-24">
    <ol class="breadcrumb breadcrumb-inverse">
      {% block  breadcrumb %}
      <li><a href="{% url 'core:home' %}">Home</a></li>
      <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
      {% endblock  %}
    </ol>
  </div>

  <div class="pure-u-1-24">

  </div>

  <div class="pure-u-6-24">
    <!--Card Light-->
    <div class="card box-panel">
      <!--Card image-->
      <div class="view overlay hm-white-slight">

      </div>
      <!--/.Card image-->
      <!--Card content-->
      <div class="card-block">
        <ul class="pure-menu-list">
          <li class="pure-menu-heading border-button">Bem-Vindo, {{ user }}</li>
          {% block menu_options %}
          {%  load_my_courses user as enrollments %}
            <li class="pure-menu-heading border-button ">Meus Cursos</li>
          {% for enrollment in enrollments  %}
            <li class="pure-menu-item" >
              <a href="{% url 'course:announcements' enrollment.course.slug %}" class="list-group-item">
              <i class="fa fa-book" aria-hidden="true"></i> {{ enrollment.course}}
            </a>
          </li>
          {% empty %}
            <li class="list-group-item">Nenhum curso encontrado</li>
          {% endfor %}
            <li class="pure-menu-heading border-button ">Configurações de Conta</li>
            <li class="pure-menu-item"><a class="list-group-item" href="{% url 'accounts:edit' %}"><i class="fa fa-cogs" aria-hidden="true"></i> Editar Conta</a></li>
            <li class="pure-menu-item"><a class="list-group-item" href="{% url 'accounts:edit_password' %}"><i class="fa fa-lock" aria-hidden="true"></i> Atualizar Senha</a></li>
          {% endblock menu_options %}
        </ul>
        <!--Text-->
      </div>
      <!--/.Card content-->
    </div>
    <!--/.Card Light-->
  </div>
  <div class="pure-u-1-24">
  </div>

  <div class="pure-u-3-5">

    {% block dashboard_content %}
    <div class="pure-u-1-24"></div>
    <legend>Meus Cursos</legend>
    {% for  enrollment in enrollments  %}
    <div class="card box-panel">
      <!--Card content-->
      <div class="card-block">
        <div class="card card-dark">
          <!--Title-->
          <h4 class="card-title bold">{{ enrollment.course }}  ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Não informado data de inicío' }})</h4>
          <p>{{ enrollment.course.description |linebreaks}}</p>
          <p>
            <a href="{% url 'course:announcements' enrollment.course.slug %}" class="button-primary pure-button"><i class="fa fa-sign-in" aria-hidden="true"></i> Acessar</a>
            <a href="{% url 'course:undo_enrollment' enrollment.course.slug %}" class="button-error pure-button"> <i class="fa fa-ban" aria-hidden="true"></i> Cancelar </a>
          </p>
        </div>
      </div>
      <!--/.Card content-->
    </div>
    {% empty %}
    <div class="pure-u-24-24 text-center">
          <p class="alert alert-info">Nenhum Cursos encontrado.</p>
    </div>
    {% endfor %}

    {% endblock  %}


  </div>
</div>
{% endblock %}

simplemooc/simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}
{% load static %}
{% block  breadcrumb %}
{{ block.super}}
<li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock  %}

{% block dashboard_content %}
{% if success %}
<div class="alert alert-success">
    <p>Imformações atualizadas com sucesso! :D</p>
</div>
{% else %}
        <p>Informe novos dados para atualização</p>
{% endif %}



<form class="pure-form pure-form-stacked" method="POST">
    {% csrf_token %}
    <fieldset>

        {{ form.non.field.errors }}
         {% for field in form   %}
        {{ field.label_tag}}
        {{ field }}
        <h6> {{ field.help_text }}</h6>
        {% if field.errors  %}
        <div class="alert alert-danger">
            {{ field.errors }}
        </div>
        {% endif %}
        {% endfor %}
        <br>
        <button type="submit" class="pure-button pure-button-primary">Salvar <i class="fa fa-floppy-o" aria-hidden="true"></i></button>
    </fieldset>
</form>
{% endblock  %}

simplemooc/simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}
{% load static %}
{% block  breadcrumb %}
{{ block.super}}
<li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock  %}

{% block dashboard_content %}
{% if success %}
<div class="alert alert-success">
    <p>Imformações atualizadas com sucesso! :D</p>
</div>
{% else %}
        <p>Informe novos dados para atualização</p>
{% endif %}



<form class="pure-form pure-form-stacked" method="POST">
    {% csrf_token %}
    <fieldset>

        {{ form.non.field.errors }}
         {% for field in form   %}
        {{ field.label_tag}}
        {{ field }}
        <h6> {{ field.help_text }}</h6>
        {% if field.errors  %}
        <div class="alert alert-danger">
            {{ field.errors }}
        </div>
        {% endif %}
        {% endfor %}
        <br>
        <button type="submit" class="pure-button pure-button-primary">Salvar Nova Senha <i class="fa fa-floppy-o" aria-hidden="true"></i></button>
    </fieldset>
</form>
{% endblock  %}

simplemooc/simplemooc/accounts/templates/accounts/login.html
<!doctype html>
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="pure-g">
    <div class="pure-u-9-24">
    </div>
    <div class="pure-u-7-24">
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Iniciar Sessão</legend>
                <h5>Informe seus dados para acessar o sistema</h5>
                 {% for field in form   %}
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
                {% endfor %}
                <button type="submit" class="pure-button pure-button-primary">Entrar</button>
            </fieldset>
        </form>
    </div>
    <div class="pure-u-9-24">

    </div>
    <div class="pure-u-9-24">
        <span>Não possue conta ?</span> <a href="{% url 'accounts:register' %}">Cadastre-se</a><br>
        <span>Esqueceu a Senha ? </span><a href="{% url 'accounts:password_reset' %}">Nova Senha</a><br>
    </div>
</div>



{% endblock %}

simplemooc/simplemooc/accounts/templates/accounts/password_reset.html
<!doctype html>
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="pure-g">
{% if success %}
    <div class="pure-u-6-24">
    </div>
    <div class="pure-u-12-24">
        <div class="alert alert-success text-center">
            <p> Um E-mail Foi enviado com detalhes para gerar uma nova senha nova senha <i class="fa fa-smile-o fx-5" aria-hidden="true"></i></p>
        </div>
        {% else %}
    <div class="pure-u-9-24">
    </div>
    <div class="pure-u-6-24">
        <h5>Informe seu E-mail</h5>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Recuperação de Senha</legend>
                {% for field in form   %}
                {{ field.label_tag }}
                {{ field }}
                <span class="alert-danger list-group-item">{{ field.errors }}</span>
                {% endfor %}
                <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
            </fieldset>
        </form>
        {% endif %}
    </div>
    <div class="pure-u-9-24">

    </div>
</div>



{% endblock %}

simplemooc/simplemooc/accounts/templates/accounts/password_reset_confirm.html
<!doctype html>
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="pure-g">
{% if success %}
    <div class="pure-u-6-24">
    </div>
    <div class="pure-u-12-24">
        <div class="alert alert-success text-center">
            <p> Nova senha criada com sucesso<i class="fa fa-smile-o fx-5" aria-hidden="true"></i></p>
            <p><a class='pure-button button-success'href="{% url 'accounts:login' %}"><b>Acessar Sistema</b></a> </p>
        </div>
        {% else %}
    <div class="pure-u-9-24">
    </div>
    <div class="pure-u-6-24">
        <h5>Informe uma Nova Senha</h5>
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Recuperação de Senha</legend>
                {% for field in form   %}
                {{ field.label_tag }}
                {{ field }}
                <span class="alert-danger list-group-item">{{ field.errors }}</span>
                {% endfor %}
                <button type="submit" class="pure-button pure-button-primary">Enviar</button>
            </fieldset>
        </form>
        {% endif %}
    </div>
    <div class="pure-u-9-24">

    </div>
</div>



{% endblock %}

simplemooc/simplemooc/accounts/templates/accounts/password_reset_mail.html
<p>Para criar uma nova senha de acesso clique <a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key %}" title="Resetar senha">AQUI!</a>.</p>
<p>Caso não acessar clique copie o link abaixo e cole em seu navegador padrão.</p>

simplemooc/simplemooc/accounts/templates/accounts/register.html
<!doctype html>
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="pure-g">
    <div class="pure-u-9-24">
    </div>
    <div class="pure-u-7-24">
        <form class="pure-form pure-form-stacked" method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Cadastrar-se</legend>
                <h5>Informe seus dados para cadastro</h5>
                 {% for field in form   %}
                {{ field.label_tag}}
                {{ field }}
                <h6> {{ field.help_text }}</h6>
                {{ field.errors }}
                {% endfor %}
                <br>
                <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}